name: CI Practice Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "test"
      test_type:
        description: "Test type"
        required: true
        default: "smoke"

jobs:
  autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show selected parameters
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Test type: ${{ github.event.inputs.test_type }}"

      - name: Simulate autotests
        run: |
          echo "Running ${{ github.event.inputs.test_type }} tests on ${{ github.event.inputs.environment }}"
          sleep 5
          echo "Autotests finished successfully"
